class db:

  auto = ('{SECRET_DB_USERNAME_AUTO}', '{SECRET_DB_PASSWORD_AUTO}')
  backup = ('{SECRET_DB_USERNAME_BACKUP}', '{SECRET_DB_PASSWORD_BACKUP}')
  epi = ('{SECRET_DB_USERNAME_EPI}', '{SECRET_DB_PASSWORD_EPI}')


class api:

  twitter = '{SECRET_API_AUTH_TWITTER}'
  ght = '{SECRET_API_AUTH_GHT}'
  signals = '{SECRET_API_AUTH_SIGNALS}'
  ilinet = '{SECRET_API_AUTH_ILINET}'
  stateili = '{SECRET_API_AUTH_STATEILI}'
  cdc = '{SECRET_API_AUTH_CDC}'
  sensors = '{SECRET_API_AUTH_SENSORS}'

class flusight:
  
  login = ('{SECRET_FLUSIGHT_LOGIN_EMAIL}', '{SECRET_FLUSIGHT_LOGIN_PASSWORD}')
